#!/bin/bash
# lib/service.sh — pcscd smart card daemon management
#
# Provides: record_pcscd_state, enable_pcscd, verify_pcscd_service, disable_pcscd
#
# On Arch/CachyOS, pcscd uses socket activation. pcscd.socket must be both
# enabled (survives reboot) and started (active in the current session).
# Managing pcscd.service alone is incorrect — socket activation requires
# pcscd.socket. Addresses KNOWN_ISSUES.md #P8.
#
# No set -euo pipefail — inherited from bash/install.sh or bash/uninstall.sh.

# Path for the udev rules file written at install time.
# Override via environment variable (used in BATS tests).
: "${_CCID_RULES_FILE:=/etc/udev/rules.d/99-cac-ccid.rules}"

record_pcscd_state() {
    # Capture whether pcscd.socket was active before we touched it so the
    # uninstall flow can decide whether to disable it.
    local was_active="false"
    if systemctl is-active --quiet pcscd.socket 2>/dev/null; then
        was_active="true"
    fi
    echo "STATE:pcscd_was_active_before=${was_active}"
    log_info "pcscd.socket active before setup: $was_active"
}

_write_ccid_udev_rules() {
    # Scan sysfs for currently connected USB CCID interfaces (class 0b) and
    # write per-device ATTRS{idVendor}/ATTRS{idProduct} udev rules that grant
    # the pcscd group r/w access to those device nodes.
    #
    # pcscd runs as the 'pcscd' user (not root). The class-based rule in
    # 92_pcscd_ccid.rules uses ENV{ID_USB_INTERFACES}=="*:0b0000:*" but only
    # fires on ACTION=="add". VID:PID rules fire on both add AND change, making
    # them reliable for readers connected before ccid was installed.
    # See KNOWN_ISSUES.md #5e.
    local tmp_rules
    tmp_rules="$(mktemp)"
    {
        printf '# Generated by cac_for_linux_distros install\n'
        printf '# Grants the pcscd group access to CCID smart card readers\n'
        printf '# detected at install time. Removed by cac_uninstall.py.\n'
    } > "$tmp_rules"

    local found=0
    local iface_name dev_dir iface_class vendor product
    if [[ -d /sys/bus/usb/devices ]]; then
        for sysfs_iface in /sys/bus/usb/devices/*:*/; do
            [[ -f "${sysfs_iface}bInterfaceClass" ]] || continue
            iface_class=$(<"${sysfs_iface}bInterfaceClass")
            [[ "$iface_class" == "0b" ]] || continue
            # Interface device name is e.g. "1-1.2:1.0"; strip ":config.iface"
            # to get the parent USB device name "1-1.2".
            iface_name="$(basename "${sysfs_iface%/}")"
            dev_dir="/sys/bus/usb/devices/${iface_name%%:*}"
            [[ -f "$dev_dir/idVendor" && -f "$dev_dir/idProduct" ]] || continue
            vendor=$(<"$dev_dir/idVendor")
            product=$(<"$dev_dir/idProduct")
            printf 'ATTRS{idVendor}=="%s", ATTRS{idProduct}=="%s", GROUP="pcscd"\n' \
                "$vendor" "$product" >> "$tmp_rules"
            found=$(( found + 1 ))
            log_info "Detected CCID reader: VID=${vendor} PID=${product}"
        done
    fi

    mv "$tmp_rules" "${_CCID_RULES_FILE}"
    if [[ $found -eq 0 ]]; then
        log_warn "No CCID readers detected at install time — if a reader is already connected, disconnect and reconnect it after setup."
    fi
}

enable_pcscd() {
    log_section "Smart Card Daemon"

    # Both enable AND start are required:
    # - enable: registers the unit for next boot
    # - start:  activates it in the current session without a reboot
    if ! log_cmd systemctl enable "${PCSCD_UNIT}"; then
        log_error "Failed to enable ${PCSCD_UNIT}"
        exit 1
    fi
    if ! log_cmd systemctl start "${PCSCD_UNIT}"; then
        log_error "Failed to start ${PCSCD_UNIT}"
        exit 1
    fi

    # pcscd runs as 'pcscd' (non-root). A reader connected before ccid was
    # installed keeps device-node group=root, denying pcscd O_RDWR access.
    # Fix: (1) scan sysfs for connected CCID readers and write per-device
    # VID:PID udev rules (fire on add AND change); (2) trigger with
    # --action=add so the class-based rule in 92_pcscd_ccid.rules also fires.
    # See KNOWN_ISSUES.md #5e.
    log_info "Scanning for connected CCID card readers..."
    _write_ccid_udev_rules
    log_info "Applying udev rules to USB devices..."
    udevadm control --reload-rules 2>/dev/null || true
    udevadm trigger --action=add --subsystem-match=usb 2>/dev/null || true
    udevadm settle --timeout=5 2>/dev/null || true

    # Explicitly start pcscd.service so it scans for card readers now, during
    # install, after the udev trigger above has set correct device permissions.
    # Without this, socket activation may start pcscd.service at some later
    # arbitrary point, possibly before a manual udev trigger is run.
    log_info "Starting pcscd.service to scan for connected card readers..."
    if ! log_cmd systemctl start pcscd.service; then
        log_warn "pcscd.service did not start — it will start on first PKCS11 connection"
    fi

    log_success "${PCSCD_UNIT} enabled and started."
    echo "ACTION:service_enable|${PCSCD_UNIT}|was_enabled_before=false"
    echo "ACTION:service_start|${PCSCD_UNIT}|was_active_before=false"
}

verify_pcscd_service() {
    # Returns 0 if pcscd.socket is active, non-zero otherwise.
    # Callers should check the return code; this function does not exit on failure.
    systemctl is-active --quiet "${PCSCD_UNIT}"
}

disable_pcscd() {
    # Used by uninstall script. Stops and disables pcscd.socket and pcscd.service.
    # Also removes the CCID udev rules file written by enable_pcscd.
    # Errors are non-fatal (units may already be stopped/disabled).
    log_info "Stopping and disabling pcscd..."
    systemctl stop pcscd.socket pcscd.service 2>/dev/null || true
    systemctl disable pcscd.socket 2>/dev/null || true
    if [[ -f "${_CCID_RULES_FILE}" ]]; then
        rm -f "${_CCID_RULES_FILE}"
        udevadm control --reload-rules 2>/dev/null || true
        log_info "Removed CCID udev rules: ${_CCID_RULES_FILE}"
    fi
    log_success "pcscd disabled."
}
